### ISSUE TITLE
Opening brain file: no such table: info

### ISSUE THREAD

**Issue by mindcombatant** [go-telegram-bot/yatzie#2]
every time i start this up, it fails with "Opening brain file: no such table: info" in the log. i've tried starting it with no existing file, a blank file, and a blank brain created with the tools at https://github.com/pteichman/cobe , none work. i'm pretty sure i need a blank brain in json format, but i can't find any tools to make that. sorry for the dumb question.

**Comment by mudler** [comment]
Hi,

Thanks to bring this to my attention !

It's not a dumb question, i completely forgot to update README to reflect recent changes with the brain engines :)

I just updated the readme with the new syntax, just let me know if you still face any issues: https://github.com/go-telegram-bot/yatzie/commit/ac85439d7abbe9c9439bc88a45982c8b3d8af8ce

Cheers!

**Comment by mindcombatant** [comment]
thank you, that helped a lot!
